#!/bin/sh

# Cerbere is elementary OS's process watchdog.
# Adding Desktop Folder to Cerbere's monitored processes list should automatically start Desktop Folder.

#SCHEMA="org.pantheon.desktop.cerbere"
#KEY="monitored-processes"
#
#APP="com.github.spheras.desktopfolder"
#LIST=$(gsettings get $SCHEMA $KEY)
#
#if [[ ! -e "/usr/share/glib-2.0/schemas/10_org.pantheon.cerbere.gschema.override" ]]; then
#    echo "No need to remove override because it doesn't exist!"
#else
#    rm /usr/share/glib-2.0/schemas/10_org.pantheon.cerbere.gschema.override
#    echo "Removed override."
#fi

killall com.github.spheras.desktopfolder

exit 0
